# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dbBasket.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(684, 483)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(20, 10, 650, 341))
        self.tableView.setObjectName("tableView")
        self.apply = QtWidgets.QPushButton(self.centralwidget)
        self.apply.setGeometry(QtCore.QRect(530, 400, 140, 30))
        self.apply.setObjectName("apply")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 370, 80, 30))
        self.label.setObjectName("label")
        self.sum = QtWidgets.QLabel(self.centralwidget)
        self.sum.setGeometry(QtCore.QRect(100, 370, 100, 30))
        self.sum.setText("")
        self.sum.setObjectName("sum")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 400, 80, 30))
        self.label_2.setObjectName("label_2")
        self.onAccount = QtWidgets.QLabel(self.centralwidget)
        self.onAccount.setGeometry(QtCore.QRect(100, 400, 100, 30))
        self.onAccount.setObjectName("onAccount")
        self.purchase = QtWidgets.QLabel(self.centralwidget)
        self.purchase.setGeometry(QtCore.QRect(200, 400, 300, 30))
        self.purchase.setText("")
        self.purchase.setObjectName("purchase")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 684, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Корзина"))
        self.apply.setText(_translate("MainWindow", "Оформить"))
        self.label.setText(_translate("MainWindow", "Общая сумма"))
        self.label_2.setText(_translate("MainWindow", "На счету"))
        self.onAccount.setText(_translate("MainWindow", "100000"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
